#!/usr/bin/env bash

# Update Package List
su root

apt-get update

apt-get upgrade -y

# Install Some PPAs

apt-get install -y software-properties-common

apt-add-repository ppa:nginx/stable -y
apt-add-repository ppa:ondrej/php-7.0 -y

# Update Package Lists

apt-get update

# Install Some Basic Packages

apt-get install -y curl dos2unix gcc git libmcrypt4 libpcre3-dev \
make python2.7-dev python-pip re2c supervisor unattended-upgrades whois vim git-flow git-core language-pack-zh*

apt-get install openssl libssl-dev libjpeg-dev libpng-dev libmcrypt-dev libreadline6 libreadline6-dev libcurl4-gnutls-dev

# Set My Timezone

ln -sf /usr/share/zoneinfo/PRC /etc/localtime

# Useradd www and Groupadd www

groupadd www
useradd www -g www -m

# Install PHP Stuffs

apt-get install -y php7.0-cli php7.0-dev php-pear \
php7.0-json php7.0-curl php7.0-gd \
php7.0-imap php7.0-mcrypt \

php7.0-mysqlnd php7.0-apcu php7.0-gmp php7.0-xdebug php7.0-memcached php7.0-redis php7.0-imagick

pecl install mongo
echo "extension=mongo.so" > /etc/php7/mods-available/mongo.ini
ln -s /etc/php7/mods-available/mongo.ini /etc/php7/cli/conf.d/20-mongo.ini

echo "extension=mcrypt.so" > /etc/php7/mods-available/mcrypt.ini
ln -s /etc/php7/mods-available/mcrypt.ini /etc/php7/cli/conf.d/20-mcrypt.ini

# Install Composer

curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

# Add Composer Global Bin To Path

printf "\nPATH=\"/root/.composer/vendor/bin:\$PATH\"\n" | tee -a /root/.profile

# Install Laravel Envoy

sudo su root <<'EOF'
/usr/local/bin/composer global require "laravel/envoy=~1.0"
EOF

# Set Some PHP CLI Settings

sudo sed -i "s/error_reporting = .*/error_reporting = E_ALL/" /etc/php7/cli/php.ini
sudo sed -i "s/display_errors = .*/display_errors = On/" /etc/php7/cli/php.ini
sudo sed -i "s/memory_limit = .*/memory_limit = 512M/" /etc/php7/cli/php.ini
sudo sed -i "s/post_max_size = .*/post_max_size = 10M/" /etc/php7/cli/php.ini
sudo sed -i "s/upload_max_filesize = .*/upload_max_filesize = 10M/" /etc/php7/cli/php.ini
sudo sed -i "s/;date.timezone.*/date.timezone = PRC/" /etc/php7/cli/php.ini

# Install Nginx & PHP-FPM

apt-get install -y nginx php7.0-fpm

rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
service nginx restart

# Setup Some PHP-FPM Options

ln -s /etc/php7/mods-available/mailparse.ini /etc/php7/fpm/conf.d/20-mailparse.ini
ln -s /etc/php7/mods-available/mongo.ini /etc/php7/fpm/conf.d/20-mongo.ini
ln -s /etc/php7/mods-available/mcrypt.ini /etc/php7/fpm/conf.d/20-mcrypt.ini

sed -i "s/error_reporting = .*/error_reporting = E_ALL/" /etc/php7/fpm/php.ini
sed -i "s/display_errors = .*/display_errors = On/" /etc/php7/fpm/php.ini
sed -i "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/" /etc/php7/fpm/php.ini
sed -i "s/memory_limit = .*/memory_limit = 512M/" /etc/php7/fpm/php.ini
sed -i "s/post_max_size = .*/post_max_size = 10M/" /etc/php7/fpm/php.ini
sed -i "s/upload_max_filesize = .*/upload_max_filesize = 10M/" /etc/php7/fpm/php.ini
sed -i "s/;date.timezone.*/date.timezone = PRC/" /etc/php7/fpm/php.ini

echo "xdebug.remote_enable = 1" >> /etc/php7/fpm/conf.d/20-xdebug.ini
echo "xdebug.remote_connect_back = 1" >> /etc/php7/fpm/conf.d/20-xdebug.ini
echo "xdebug.remote_port = 9000" >> /etc/php7/fpm/conf.d/20-xdebug.ini

# Copy fastcgi_params to Nginx because they broke it on the PPA

cat > /etc/nginx/fastcgi_params << EOF
fastcgi_param   QUERY_STRING        \$query_string;
fastcgi_param   REQUEST_METHOD      \$request_method;
fastcgi_param   CONTENT_TYPE        \$content_type;
fastcgi_param   CONTENT_LENGTH      \$content_length;
fastcgi_param   SCRIPT_FILENAME     \$request_filename;
fastcgi_param   SCRIPT_NAME     \$fastcgi_script_name;
fastcgi_param   REQUEST_URI     \$request_uri;
fastcgi_param   DOCUMENT_URI        \$document_uri;
fastcgi_param   DOCUMENT_ROOT       \$document_root;
fastcgi_param   SERVER_PROTOCOL     \$server_protocol;
fastcgi_param   GATEWAY_INTERFACE   CGI/1.1;
fastcgi_param   SERVER_SOFTWARE     nginx/\$nginx_version;
fastcgi_param   REMOTE_ADDR     \$remote_addr;
fastcgi_param   REMOTE_PORT     \$remote_port;
fastcgi_param   SERVER_ADDR     \$server_addr;
fastcgi_param   SERVER_PORT     \$server_port;
fastcgi_param   SERVER_NAME     \$server_name;
fastcgi_param   HTTPS           \$https if_not_empty;
fastcgi_param   REDIRECT_STATUS     200;
EOF

# Set The Nginx & PHP-FPM User

sed -i "s/user www-data;/user www;/" /etc/nginx/nginx.conf
sed -i "s/# server_names_hash_bucket_size.*/server_names_hash_bucket_size 64;/" /etc/nginx/nginx.conf

sed -i "s/user = www-data/user = www/" /etc/php7/fpm/pool.d/www.conf
sed -i "s/group = www-data/group = www/" /etc/php7/fpm/pool.d/www.conf

sed -i "s/;listen\.owner.*/listen.owner = www/" /etc/php7/fpm/pool.d/www.conf
sed -i "s/;listen\.group.*/listen.group = www/" /etc/php7/fpm/pool.d/www.conf
sed -i "s/;listen\.mode.*/listen.mode = 0666/" /etc/php7/fpm/pool.d/www.conf

service nginx restart
service php7.0-fpm restart
